import type { INodeProperties } from 'n8n-workflow';

const resourceOptions = [
	{ name: 'Account', value: 'account' },
	{ name: 'Brand Campaign', value: 'campaign' },
	{ name: 'Contact', value: 'contact' },
	{ name: 'Message', value: 'message' },
	{ name: 'Number Lookup', value: 'numberLookup' },
	{ name: 'Profile', value: 'profile' },
	{ name: 'Template', value: 'template' },
	{ name: 'User', value: 'user' },
	{ name: 'Webhook', value: 'webhook' },
];

const operations: Record<string, Array<{ name: string; value: string; action: string }>> = {
	account: [{ name: 'Get', value: 'get', action: 'Get authenticated account' }],
	campaign: [
		{ name: 'Create', value: 'create', action: 'Create a brand campaign' },
		{ name: 'Delete', value: 'delete', action: 'Delete a brand campaign' },
		{ name: 'Get Many', value: 'getMany', action: 'Get many brand campaigns' },
		{ name: 'Update', value: 'update', action: 'Update a brand campaign' },
	],
	contact: [
		{ name: 'Delete', value: 'delete', action: 'Delete a contact' },
		{ name: 'Get', value: 'get', action: 'Get a contact' },
		{ name: 'Get Many', value: 'getMany', action: 'Get many contacts' },
	],
	message: [
		{ name: 'Get', value: 'get', action: 'Get a message' },
		{ name: 'Get Activities', value: 'getActivities', action: 'Get message activities' },
		{ name: 'Send', value: 'send', action: 'Send a message' },
	],
	numberLookup: [{ name: 'Lookup', value: 'lookup', action: 'Look up a phone number' }],
	profile: [
		{ name: 'Complete Setup', value: 'complete', action: 'Complete profile setup' },
		{ name: 'Create', value: 'create', action: 'Create a profile' },
		{ name: 'Delete', value: 'delete', action: 'Delete a profile' },
		{ name: 'Get', value: 'get', action: 'Get a profile' },
		{ name: 'Get Many', value: 'getMany', action: 'Get many profiles' },
		{ name: 'Update', value: 'update', action: 'Update a profile' },
	],
	template: [
		{ name: 'Create', value: 'create', action: 'Create a template' },
		{ name: 'Delete', value: 'delete', action: 'Delete a template' },
		{ name: 'Get', value: 'get', action: 'Get a template' },
		{ name: 'Get Many', value: 'getMany', action: 'Get many templates' },
		{ name: 'Update', value: 'update', action: 'Update a template' },
	],
	user: [
		{ name: 'Get', value: 'get', action: 'Get a user' },
		{ name: 'Get Many', value: 'getMany', action: 'Get many users' },
		{ name: 'Invite', value: 'invite', action: 'Invite a user' },
		{ name: 'Remove', value: 'remove', action: 'Remove a user' },
		{ name: 'Update Role', value: 'updateRole', action: 'Update a user role' },
	],
	webhook: [
		{ name: 'Create', value: 'create', action: 'Create a webhook' },
		{ name: 'Delete', value: 'delete', action: 'Delete a webhook' },
		{ name: 'Get', value: 'get', action: 'Get a webhook' },
		{ name: 'Get Event Types', value: 'getEventTypes', action: 'Get webhook event types' },
		{ name: 'Get Events', value: 'getEvents', action: 'Get webhook events' },
		{ name: 'Get Many', value: 'getMany', action: 'Get many webhooks' },
		{ name: 'Rotate Signing Secret', value: 'rotateSecret', action: 'Rotate a webhook signing secret' },
		{ name: 'Test', value: 'test', action: 'Test a webhook' },
		{ name: 'Toggle Status', value: 'toggleStatus', action: 'Toggle a webhook status' },
		{ name: 'Update', value: 'update', action: 'Update a webhook' },
	],
};

const mutationOptions: INodeProperties[] = [
	{
		displayName: 'Idempotency Key',
		name: 'idempotencyKey',
		type: 'string',
		default: '',
		description: '1-255 letters, numbers, hyphens, or underscores. Reuse the same key when retrying.',
	},
	{
		displayName: 'Sandbox',
		name: 'sandbox',
		type: 'boolean',
		default: false,
		description: 'Whether Sent should validate and simulate this supported mutation without side effects',
	},
];

const idFields: INodeProperties[] = [
	{
		displayName: 'Contact ID',
		name: 'contactId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['contact'], operation: ['delete', 'get'] } },
	},
	{
		displayName: 'Message ID',
		name: 'messageId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['message'], operation: ['get', 'getActivities'] } },
	},
	{
		displayName: 'Profile ID',
		name: 'profileId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['profile'], operation: ['complete', 'delete', 'get', 'update'] } },
	},
	{
		displayName: 'Profile ID',
		name: 'profileId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['campaign'], operation: ['create', 'delete', 'getMany', 'update'] } },
	},
	{
		displayName: 'Campaign ID',
		name: 'campaignId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['campaign'], operation: ['delete', 'update'] } },
	},
	{
		displayName: 'Template ID',
		name: 'templateId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['template'], operation: ['delete', 'get', 'update'] } },
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['user'], operation: ['get', 'remove', 'updateRole'] } },
	},
	{
		displayName: 'Webhook ID',
		name: 'webhookId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['webhook'], operation: ['delete', 'get', 'getEvents', 'rotateSecret', 'test', 'toggleStatus', 'update'] } },
	},
];

const paginationFields: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['contact', 'template', 'webhook'],
				operation: ['getMany', 'getEvents'],
			},
		},
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		displayOptions: {
			show: {
				resource: ['contact', 'template', 'webhook'],
				operation: ['getMany', 'getEvents'],
				returnAll: [false],
			},
		},
		description: 'Max number of results to return',
	},
];

export const sentProperties: INodeProperties[] = [
	{
		displayName: 'Resource',
		name: 'resource',
		type: 'options',
		noDataExpression: true,
		options: resourceOptions,
		default: 'message',
	},
	...Object.entries(operations).map(([resource, resourceOperations]) => ({
		displayName: 'Operation',
		name: 'operation',
		type: 'options' as const,
		noDataExpression: true,
		options: resourceOperations,
		default: resourceOperations[0].value,
		displayOptions: { show: { resource: [resource] } },
	})),
	...idFields,
	{
		displayName: 'Phone Number',
		name: 'phoneNumber',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'e.g. +14155550123',
		displayOptions: { show: { resource: ['numberLookup'], operation: ['lookup'] } },
		description: 'Phone number in an international format accepted by Sent',
	},
	{
		displayName: 'Recipients',
		name: 'recipients',
		type: 'string',
		required: true,
		default: '',
		// Both numbers are reserved for fiction: NANP 555-01xx and Ofcom's 020 7946 0xxx
		// drama range. Never put an allocatable number in a copy-pasteable placeholder.
		placeholder: 'e.g. +14155550123,+442079460123',
		displayOptions: { show: { resource: ['message'], operation: ['send'] } },
		description: 'Comma-separated recipient phone numbers',
	},
	{
		displayName: 'Channels',
		name: 'channels',
		type: 'multiOptions',
		options: [
			{ name: 'Sent (Automatic Routing)', value: 'sent' },
			{ name: 'RCS', value: 'rcs' },
			{ name: 'SMS', value: 'sms' },
			{ name: 'WhatsApp', value: 'whatsapp' },
		],
		default: ['sent'],
		displayOptions: { show: { resource: ['message'], operation: ['send'] } },
		description: 'Sent uses automatic routing. Several explicit channels create a broadcast, not a fallback order.',
	},
	{
		displayName: 'Message Type',
		name: 'messageType',
		type: 'options',
		options: [
			{ name: 'Template', value: 'template' },
			{ name: 'Text', value: 'text' },
		],
		default: 'template',
		displayOptions: { show: { resource: ['message'], operation: ['send'] } },
	},
	{
		displayName: 'Template',
		name: 'messageTemplate',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		modes: [
			{ displayName: 'From List', name: 'list', type: 'list', typeOptions: { searchListMethod: 'getTemplates', searchable: true } },
			{ displayName: 'ID', name: 'id', type: 'string' },
			{ displayName: 'Name', name: 'name', type: 'string' },
		],
		displayOptions: { show: { resource: ['message'], operation: ['send'], messageType: ['template'] } },
		description: 'Template name or ID to use',
	},
	{
		displayName: 'Template Parameters',
		name: 'templateParameters',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['message'], operation: ['send'], messageType: ['template'] } },
		description: 'JSON object whose keys match the template variables',
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		typeOptions: { rows: 4 },
		required: true,
		default: '',
		displayOptions: { show: { resource: ['message'], operation: ['send'], messageType: ['text'] } },
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'e.g. person@example.com',
		displayOptions: { show: { resource: ['user'], operation: ['invite'] } },
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['profile', 'user'], operation: ['create', 'update', 'invite'] } },
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['template'], operation: ['update'] } },
	},
	{
		displayName: 'Role',
		name: 'role',
		type: 'options',
		options: [
			{ name: 'Admin', value: 'admin' },
			{ name: 'Billing', value: 'billing' },
			{ name: 'Developer', value: 'developer' },
		],
		default: 'developer',
		displayOptions: { show: { resource: ['user'], operation: ['invite', 'updateRole'] } },
	},
	{
		displayName: 'Template Category',
		name: 'category',
		type: 'options',
		options: [
			{ name: 'Authentication', value: 'AUTHENTICATION' },
			{ name: 'Marketing', value: 'MARKETING' },
			{ name: 'Utility', value: 'UTILITY' },
		],
		default: 'UTILITY',
		displayOptions: { show: { resource: ['template'], operation: ['create', 'update'] } },
	},
	{
		displayName: 'Language',
		name: 'language',
		type: 'string',
		default: 'en_US',
		displayOptions: { show: { resource: ['template'], operation: ['create', 'update'] } },
	},
	{
		displayName: 'Definition JSON',
		name: 'definitionJson',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['template'], operation: ['create', 'update'] } },
		description: 'Template definition object following the Sent Template Definition reference',
	},
	{
		displayName: 'Creation Source',
		name: 'creationSource',
		type: 'string',
		default: 'from-api',
		displayOptions: { show: { resource: ['template'], operation: ['create'] } },
		description: 'Optional source label recorded by Sent',
	},
	{
		displayName: 'Submit for Review',
		name: 'submitForReview',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['template'], operation: ['create', 'update'] } },
		description: 'Whether to submit the template for review instead of saving it as a draft',
	},
	{
		displayName: 'Campaign JSON',
		name: 'campaignJson',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['campaign'], operation: ['create', 'update'] } },
		description: 'Campaign object following the Sent brand campaign schema',
	},
	{
		displayName: 'Webhook URL',
		name: 'webhookUrl',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['profile'], operation: ['complete'] } },
		description: 'Public callback URL that receives the profile completion result',
	},
	{
		displayName: 'Display Name',
		name: 'displayName',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['webhook'], operation: ['create', 'update'] } },
	},
	{
		displayName: 'Endpoint URL',
		name: 'endpointUrl',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['webhook'], operation: ['create', 'update'] } },
	},
	{
		displayName: 'Event Types',
		name: 'eventTypes',
		type: 'multiOptions',
		options: [
			{ name: 'Message', value: 'message' },
			{ name: 'Templates', value: 'templates' },
		],
		default: ['message'],
		displayOptions: { show: { resource: ['webhook'], operation: ['create', 'update'] } },
	},
	{
		displayName: 'Event Filters JSON',
		name: 'eventFiltersJson',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['webhook'], operation: ['create', 'update'] } },
		description: 'Optional parent-to-subtype map, for example {"message":["delivered","failed"]}',
	},
	{
		displayName: 'Retry Count',
		name: 'retryCount',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 5 },
		default: 3,
		displayOptions: { show: { resource: ['webhook'], operation: ['create', 'update'] } },
		description: 'Number of delivery attempts per event',
	},
	{
		displayName: 'Timeout Seconds',
		name: 'timeoutSeconds',
		type: 'number',
		typeOptions: { minValue: 5, maxValue: 120 },
		default: 30,
		displayOptions: { show: { resource: ['webhook'], operation: ['create', 'update'] } },
		description: 'Maximum time Sent waits for the endpoint response',
	},
	{
		displayName: 'Event Type',
		name: 'eventType',
		type: 'string',
		default: 'message.sent',
		displayOptions: { show: { resource: ['webhook'], operation: ['test'] } },
	},
	{
		displayName: 'Is Active',
		name: 'isActive',
		type: 'boolean',
		default: true,
		displayOptions: { show: { resource: ['webhook'], operation: ['toggleStatus'] } },
	},
	{
		displayName: 'Additional Fields JSON',
		name: 'additionalFieldsJson',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['profile'], operation: ['create', 'update'] } },
		description: 'Additional documented profile fields, including nested billing and brand objects',
	},
	...paginationFields,
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['contact'], operation: ['getMany'] } },
		options: [
			{ displayName: 'Channel', name: 'channel', type: 'options', options: [{ name: 'SMS', value: 'sms' }, { name: 'WhatsApp', value: 'whatsapp' }], default: 'sms' },
			{ displayName: 'Phone', name: 'phone', type: 'string', default: '' },
			{ displayName: 'Search', name: 'search', type: 'string', default: '' },
		],
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['template'], operation: ['getMany'] } },
		options: [
			{
				displayName: 'Category',
				name: 'category',
				type: 'options',
				options: [
					{ name: 'Authentication', value: 'AUTHENTICATION' },
					{ name: 'Marketing', value: 'MARKETING' },
					{ name: 'Utility', value: 'UTILITY' },
				],
				default: 'UTILITY',
			},
			{ displayName: 'Is Welcome Playground', name: 'isWelcomePlayground', type: 'boolean', default: false },
			{ displayName: 'Search', name: 'search', type: 'string', default: '' },
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Approved', value: 'APPROVED' },
					{ name: 'Pending', value: 'PENDING' },
					{ name: 'Rejected', value: 'REJECTED' },
				],
				default: 'APPROVED',
			},
		],
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['webhook'], operation: ['getMany'] } },
		options: [
			{ displayName: 'Is Active', name: 'isActive', type: 'boolean', default: true },
			{ displayName: 'Search', name: 'search', type: 'string', default: '' },
		],
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['webhook'], operation: ['getEvents'] } },
		options: [{ displayName: 'Search', name: 'search', type: 'string', default: '' }],
	},
	// One Options collection covers every mutation. It is declared twice under the
	// same name because `Webhook → Delete` documents neither sandbox nor idempotency
	// support, and n8n hides a parameter as soon as *any* `hide` rule matches — so
	// "all mutations except webhook delete" cannot be expressed in one rule set.
	{
		displayName: 'Options',
		name: 'requestOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				operation: ['complete', 'create', 'invite', 'remove', 'rotateSecret', 'send', 'test', 'toggleStatus', 'update', 'updateRole'],
			},
		},
		options: mutationOptions,
	},
	{
		displayName: 'Options',
		name: 'requestOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['campaign', 'contact', 'profile', 'template'], operation: ['delete'] } },
		options: mutationOptions,
	},
];
